[package]
name = "treepro"
version = "0.1.0"
authors = ["Marco De Nittis <marco.denittis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
